services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: book
      MONGO_INITDB_ROOT_PASSWORD: book
      MONGO_INITDB_DATABASE: book
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: [ "mongod", "--auth" ]

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: book
      ME_CONFIG_MONGODB_ADMINPASSWORD: book
      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/book?authSource=admin
      ME_CONFIG_MONGODB_URL: mongodb://book:book@mongo:27017/book?authSource=admin
