spring:
  application:
    name: demo
  data:
    mongodb:
      url: mongodb://localhost:27017/book
      username: book
      password: book
      database: book
#      uri: mongodb://book:book@localhost:27017/book

#  datasource:
#    url: jdbc:mysql://localhost:3306/book
#    username: book
#    password: book
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: validate
#    show-sql: true
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#  flyway:
#    url: jdbc:mysql://localhost:3306/book
#    user: book
#    password: book
#    schemas: book
#    baseline-on-migrate: true





